
if [ -f config-akash ]; then
  echo Importing config-akash
  . config-akash
else
  echo config-akash not found
fi

dump_variables () {
  echo SSH_PUBKEY=$SSH_PUBKEY
  echo DOCKER_CONTAINER=$DOCKER_CONTAINER
}

dump_variables

#read
#SSH_PUBKEY

SSH_PUBKEY=AAAAB3NzaC1yc2EAAAABIwAAAQEAr1N8b

echo "# Generated by configure.sh" >> config-akash
echo "export SSH_PUBKEY=$SSH_PUBKEY" >> config-akash
echo "export DOCKER_CONTAINER=$DOCKER_CONTAINER" >> config-akash
