# Default
SSH_PUBKEY=AAAAB3NzaC1yc2EAAAABIwAAAQEAr1N8b
SSH_PUBKEY1=AAAAB3NzaC1yc2EAAAABIwAAAQEAr1N8b
DOCKER_CONTAINER=username/compute-27-akash:0.1-dev
NETUID=15
NETWORK=test
WALLET_NAME=default
WALLET_HOTKEY=default
WANDB_KEY=
SSH_PORT=22
MINER=true
VALIDATOR=false

if [ -f config-akash ]; then
  echo Importing config-akash
  . config-akash
else
  echo config-akash not found
fi

. lib.sh

dump_variables

#read
#SSH_PUBKEY


echo Creating config-akash
echo "# Generated by configure.sh" > config-akash
echo "export SSH_PUBKEY=$SSH_PUBKEY" >> config-akash
echo "export SSH_PUBKEY1=$SSH_PUBKEY1" >> config-akash
echo "export DOCKER_CONTAINER=$DOCKER_CONTAINER" >> config-akash
echo "export NETUID=$NETUID" >> config-akash
echo "export NETWORK=$NETWORK" >> config-akash
echo "export WALLET_NAME=$WALLET_NAME" >> config-akash
echo "export WALLET_HOTKEY=$WALLET_HOTKEY" >> config-akash
echo "export WANDB_KEY=$WANDB_KEY" >> config-akash
echo "export SSH_PORT=$SSH_PORT" >> config-akash
echo "export MINER=$MINER" >> config-akash
echo "export VALIDATOR=$VALIDATOR" >> config-akash
echo "echo Config imported!" >> config-akash

echo Modify config-akash for your options
