
if [ -f config-akash ]; then
  echo Importing config-akash
  . config-akash
else
  echo config-akash not found
fi

dump_variables () {
  echo SSH_PUBKEY=$SSH_PUBKEY
  echo DOCKER_CONTAINER=$DOCKER_CONTAINER
  echo NETUID=$NETUID
  echo NETWORK=$NETWORK
  echo WALLET_NAME=$WALLET_NAME
  echo WALLET_HOTKEY=$WALLET_HOTKEY
}

dump_variables

#read
#SSH_PUBKEY

SSH_PUBKEY=AAAAB3NzaC1yc2EAAAABIwAAAQEAr1N8b
echo NETUID=15
echo NETWORK=test
echo WALLET_NAME=default
echo WALLET_HOTKEY=default

echo "# Generated by configure.sh" >> config-akash
echo "export SSH_PUBKEY=$SSH_PUBKEY" >> config-akash
echo "export DOCKER_CONTAINER=$DOCKER_CONTAINER" >> config-akash
echo "export NETUID=$NETUID" >> config-akash
echo "export NETWORK=$NETWORK" >> config-akash
echo "export WALLET_NAME=$WALLET_NAME" >> config-akash
echo "export WALLET_HOTKEY=$WALLET_HOTKEY" >> config-akash
