version: "2.0"
services:
  service-1:
    image: gojo89/compute-27-akash:0.1-dev
    env:
      - SSH_KEY=SSH_KEY_PLACEHOLDER
      - MINER=MINER_PLACEHOLDER
      - VALIDATOR=VALIDATOR_PLACEHOLDER
      - DOCKER_CONTAINER_PLACEHOLDER
      - NETUID_PLACEHOLDER
      - NETWORK_PLACEHOLDER
      - WALLET_NAME_PLACEHOLDER
      - WALLET_HOTKEY_PLACEHOLDER
    expose:
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
