---
version: "2.0"
services:
  app:
    image: gojo89/compute-27-akash:0.3-dev
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
    command:
      - bash
      - "-c"
    args:
      - >-
        apt-get update ; apt-get upgrade -y ; apt-get install vim -y ; sleep
        infinity
profiles:
  compute:
    app:
      resources:
        cpu:
          units:
            - 1
        memory:
          size: 2048Mi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: h100
                - model: a100
                - model: rtx4090
                - model: rtx3090
                - model: v100
                - model: rtx3060ti
                - model: p100
                - model: t4
                - model: A6000
                - model: A4000
  placement:
    akash:
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1
