version: "2.0"

endpoints:
 myendpoint:
   kind: ip

services:
  service-1:
    image: DOCKER_CONTAINER_PLACEHOLDER
    env:
      - SSH_KEY=SSH_KEY_PLACEHOLDER0
      - SSH_KEY1=SSH_KEY_PLACEHOLDER1
      - MINER=MINER_PLACEHOLDER
      - VALIDATOR=VALIDATOR_PLACEHOLDER
      - DOCKER_CONTAINER=DOCKER_CONTAINER_PLACEHOLDER
      - NETUID=NETUID_PLACEHOLDER
      - NETWORK=NETWORK_PLACEHOLDER
      - WALLET_NAME=WALLET_NAME_PLACEHOLDER
      - WALLET_HOTKEY=WALLET_HOTKEY_PLACEHOLDER
      - AKASH=true
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true 
            ip: myendpoint
      - port: 3070
        as: 3070
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 8980
        as: 8980
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 8091
        as: 8091
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 4444
        as: 4444
        to:
          - global: true 
            ip: myendpoint
      - port: 8091
        as: 8091
        proto: tcp
        to:
          - global: true 
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 1024Mi
        storage:
          - size: 100Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
