---
version: "2.0"

endpoints:
 myendpoint:
   kind: ip

services:
  app:
    image: ubuntu:latest     
    
    command:
      - "bash"
      - "-c"
    args:
      - 'apt-get update ;
        apt-get upgrade -y ;
        apt-get install vim curl wget git openssh-server -y ;
        git clone https://github.com/xen1024/c27-akash.git ;
        cp c27-akash/akash-0/config-akash ~/.config-akash ;
        cd c27-akash/akash-0/y-scripts && ./post-install.sh ;
        /usr/sbin/sshd -D ;
        sleep infinity'
    
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true 
            ip: myendpoint
      - port: 3070
        as: 3070
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 8980
        as: 8888
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 8400
        as: 8400
        proto: tcp
        to:
          - global: true
            ip: myendpoint
      - port: 8401
        as: 8401
        proto: tcp
        to:
          - global: true
            ip: myendpoint
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 512Mi
        storage:
          size: 100Gi
          
  placement:
    akash: 
      attributes:
            
      pricing:
        app:
          denom: uakt
          amount: 10000
deployment:
  app:
    akash:
      profile: app
      count: 1 
