version: "2.0"
services:
  service-1:
    image: DOCKER_CONTAINER_PLACEHOLDER
    env:
      - SSH_KEY=SSH_KEY_PLACEHOLDER
      - SSH_KEY1=SSH_KEY_PLACEHOLDER1
      - MINER=MINER_PLACEHOLDER
      - VALIDATOR=VALIDATOR_PLACEHOLDER
      - DOCKER_CONTAINER=DOCKER_CONTAINER_PLACEHOLDER
      - NETUID=NETUID_PLACEHOLDER
      - NETWORK=NETWORK_PLACEHOLDER
      - WALLET_NAME=WALLET_NAME_PLACEHOLDER
      - WALLET_HOTKEY=WALLET_HOTKEY_PLACEHOLDER
      - AKASH=true
    expose:
      - port: 22
        as: 22
        proto: tcp
        to:
          - global: true
      - port: 3070
        as: 3070
        proto: tcp
        to:
          - global: true
      - port: 8980
        as: 8888
        proto: tcp
        to:
          - global: true
      - port: 8400
        as: 8400
        proto: tcp
        to:
          - global: true
      - port: 8401
        as: 8401
        proto: tcp
        to:
          - global: true          
      - port: 4444
        as: 4444
        proto: tcp
        to:
          - global: true 
profiles:
  compute:
    service-1:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 100Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: a100
                  ram: 40Gi
  placement:
    dcloud:
      pricing:
        service-1:
          denom: uakt
          amount: 1000
deployment:
  service-1:
    dcloud:
      profile: service-1
      count: 1
